site/coolcad/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^materiais/', include('materiais.urls', namespace="materiais")) ,
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

site/materiais/urls.py
#coding: utf-8
from . import views
from django.conf.urls import patterns, url


urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
    url(r'^adicionar_plain', views.adicionar_plain, name="adicionar_plain"),
    url(r'^adicionar_class/$', views.adicionar_class, name='adicionar_class'),
    url(r'^adicionar_model/$', views.adicionar_model, name='adicionar_model'),
    url(r'^(?P<material_id>\d+)', views.detalhe, name="detalhe"),
    
)

site/materiais/models.py
# conding: utf-8
from django.db import models

GRUPO_ALIMENTOS, GRUPO_ALCOOLICOS, GRUPO_NAO_ALCOOLICOS, GRUPO_OUTROS = 1, 2, 3, 4


# Create your models here.
TIPO_GRUPO_CHOICES = (
    (GRUPO_ALIMENTOS, u"Alimentos"),
    (GRUPO_ALCOOLICOS, u"Alcoolicos"),
    (GRUPO_NAO_ALCOOLICOS, u"Nao Alcoolicos"),
    (GRUPO_OUTROS, u"Outros"),
)

TIPO_GRUPO_CHOICES_DICT = dict(TIPO_GRUPO_CHOICES)

class GrupoDeMaterial(models.Model):
    nome = models.CharField(max_length=50)
    tipo = models.IntegerField(choices=TIPO_GRUPO_CHOICES, default=GRUPO_OUTROS)
    
    def __unicode__(self):
        return u"{} - {}".format(self.nome, TIPO_GRUPO_CHOICES_DICT[self.tipo])

class Material(models.Model):
    codigo = models.CharField(u'codigo', max_length=20)
    descricao = models.CharField(u'descricao', max_length=100)
    unidade = models.CharField(u'unidade', max_length=2)
    grupo = models.ForeignKey(GrupoDeMaterial)
    
    
    def __unicode__(self):
        return u"{} - {}".format(self.codigo, self.descricao)

site/materiais/forms.py
#coding: utf-8

from .models import Material, GrupoDeMaterial
from django import forms

class MaterialModelForm(forms.ModelForm):
    class Meta:
        model = Material

class MaterialForm(forms.Form):
    codigo = forms.CharField(label=u'código', max_length=20)
    descricao = forms.CharField(label=u'descrição', max_length=100)
    unidade = forms.CharField(label=u'unidade', max_length=2)
    unidade = forms.CharField(label=u'unidade', max_length=2)
    grupo = forms.ModelChoiceField(
        label=u'grupo',
        queryset=GrupoDeMaterial.objects
    )

site/materiais/views.py
#coding: utf-8
from .forms import MaterialForm, MaterialModelForm
from .models import Material, GrupoDeMaterial
from django.shortcuts import render




def index(request):
    materiais = Material.objects.all()
    context = dict(nome="Colibri",
                   materiais=materiais )
    
    return render(request,'materiais/index.html', context)
    #return HttpResponse('Primeira view')
    
    
def detalhe(request, material_id):
    material = Material.objects.get(pk=int(material_id))
    context = dict(material=material)
    return render(request, 'materiais/detalhe.html', context)

def adicionar_plain(request):
    grupos = GrupoDeMaterial.objects.all()
    context = dict(
        grupos=grupos
    )
    if request.POST:
        material = Material()
        material.codigo = request.POST['codigo']
        material.descricao = request.POST['descricao']
        material.unidade = request.POST['unidade']
        material.grupo = GrupoDeMaterial.objects.get(pk=request.POST['grupo'])
        material.save()
        context['material'] = material

    return render(request, 'materiais/adicionar_plain.html', context)

def adicionar_class(request):
    context = dict()
    if request.POST:
        form=MaterialForm(request.POST)
        if form.is_valid():
            material = Material()
            material.codigo = form.cleaned_data['codigo']
            material.descricao = form.cleaned_data['descricao']
            material.unidade = form.cleaned_data['unidade']
            material.grupo = form.cleaned_data['grupo']
            material.save()
            context['material'] = material
    else:
        form=MaterialForm()

    context['form'] = form
    return render(request, 'materiais/adicionar_class.html', context)

def adicionar_model(request):
    context = dict()
    if request.POST:
        form = MaterialModelForm(request.POST)
        if form.is_valid():
            material = form.save()
            context['material'] = material
    else:
        form = MaterialModelForm()

    context['form'] = form
    return render(request, 'materiais/adicionar_class.html', context)




    

site/templates/materiais/adicionar_class.html
{% extends "materiais/materiais_base.html" %}

{% block content %}
<div class="row">
    {%if material%}
    <div class="alert alert-success">
        Material {{material}} adicionado com sucesso.
    </div>
    {%endif%}
    <h3>Cadastrar material</h3>
    <form action="." method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-default">Enviar</button>
    </form>
</div>
{% endblock content %}

site/templates/materiais/index.html
{% extends "materiais/materiais_base.html" %}

{%block content %}
    <h2>Lista de materiais</h2>
    {% if not materiais %}
        <p>Sem materiais para exibir.</p>
    {%else%}
        <ul>
        {% for m in materiais %}
            <li><a href="{% url "materiais:detalhe" m.id %}">{{m.descricao}}</a></li>
        {%endfor%}
        </ul>
    {%endif%}
{%endblock%}

site/templates/materiais/materiais_base.html
{% extends "base.html" %}

{%block main_content %}
<h1>Materiais</h1>
<div class="row">
    <div class="col-lg-2">
        <ul class="nav nav-stacked">
            <li><a href="{% url "materiais:index" %}">Lista</a></li>
            <li><a href="{% url "materiais:adicionar_plain" %}">Adicionar</a></li>
            <li><a href="{% url "materiais:adicionar_class" %}">Adicionar class</a></li>
            <li><a href="{% url "materiais:adicionar_model" %}">Adicionar model</a></li>
        </ul>
    </div>
    <div class="col-lg-10">{%block content%}{%endblock%}</div>
</div>
{%endblock%}